### ISSUE TITLE
Potential for back porting windows support to hyperlocal

### ISSUE THREAD

**Issue by softprops** [Azure/hyperlocal-windows#1]
👋maintainer of hyperlocal here. It's super cool ms is using rust and even cooler some of that rust is influenced by my work. I'm wondering if it would be possible to back port some of this to hyper local? Ideally I'd love if it we're more portable. I didn't even know domain sockets we're a thing on windows!

**Comment by damonbarry** [comment]
Definitely looking forward to moving this into hyperlocal--I don't want this repo to live any longer than necessary.

The hangup for us (Azure IoT Edge product team) is that there are also changes needed in the standard library, mio-uds, and tokio-uds, so hyperlocal is at the end of the dependency chain.

I guess we could backport to hyperlocal now and just have it depend on Azure/mio-uds-windows and Azure/tokio-uds-windows, but they aren't even published to crates.io yet. I was kind-of hoping to avoid that step but we can do it if needed.

Let me know what you think!

**Comment by softprops** [comment]
I gotcha. No worries. Very cool to see Microsoft using rust!

**Comment by arsing** [comment]
Let's discuss this in https://github.com/softprops/hyperlocal/issues/21
